"""baseline schema

Revision ID: ef7e82e2bcc5
Revises: 
Create Date: 2026-07-23 01:07:19.270547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef7e82e2bcc5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings_filter_prefs',
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('profile_id', 'key')
    )
    op.create_table('sweeps',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('repo_path', sa.String(length=512), nullable=False),
    sa.Column('repo_name', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('surfaces', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('threat_model', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('exploit_paths', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('interactive', sa.Boolean(), nullable=True),
    sa.Column('org', sa.String(length=128), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('commit_branch', sa.String(length=128), nullable=True),
    sa.Column('clone_url', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_prefs',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sweep_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['sweep_id'], ['sweeps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sweep_id', 'seq', name='uq_events_sweep_seq')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sweep_id', sa.String(length=64), nullable=False),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('class', sa.String(length=64), nullable=False),
    sa.Column('cwe', sa.String(length=32), nullable=False),
    sa.Column('file', sa.String(length=512), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('function', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['sweep_id'], ['sweeps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr_watches',
    sa.Column('sweep_id', sa.String(length=64), nullable=False),
    sa.Column('repo_full_name', sa.String(length=256), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('clone_url', sa.String(length=512), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment_status', sa.String(length=32), nullable=True),
    sa.Column('comment_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sweep_id'], ['sweeps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sweep_id')
    )
    op.create_table('sweep_jobs',
    sa.Column('sweep_id', sa.String(length=64), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sweep_id'], ['sweeps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sweep_id')
    )
    op.create_index(op.f('ix_sweep_jobs_status'), 'sweep_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sweep_jobs_status'), table_name='sweep_jobs')
    op.drop_table('sweep_jobs')
    op.drop_table('pr_watches')
    op.drop_table('findings')
    op.drop_table('events')
    op.drop_table('workspace_prefs')
    op.drop_table('sweeps')
    op.drop_table('findings_filter_prefs')
    # ### end Alembic commands ###
